import Head from 'next/head'
import ChatBot from './chatbot'
import Login from './auth/login'
import {signIn} from "next-auth/react";


export default function Home() {


  return (
    <>

      <Head>
        <title>The Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
    <button onClick={signIn}>login Here</button>
      </main>
    </>
  )
}
